#!/usr/bin/env bash
# Idempotent native development stack (loopback only):
#   1. PostgreSQL 16 cluster in .run/pg (created on first run), 127.0.0.1:55432
#   2. role/database "wildrush" with a random dev password stored in .run/dev.env (0600)
#   3. alembic upgrade head
#   4. control service on http://127.0.0.1:8080 (background; log .run/service.log, pid .run/service.pid)
# Re-running only starts what is not running. Stop with services/scripts/dev_down.sh.
set -euo pipefail
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/_dev_common.sh"

[[ -x "$PG_BIN/initdb" && -x "$PG_BIN/pg_ctl" ]] || die "PostgreSQL 16 binaries not found in $PG_BIN (set WR_PG_BIN)"
[[ -x "$PY" ]] || die "python not found at $PY (run tools/setup_env.sh)"

mkdir -p "$RUN_DIR" "$PG_DIR" "$PG_SOCK" "$ALLOC_DIR"
chmod 755 "$RUN_DIR"
if [[ "$(id -u)" -eq 0 ]]; then
  chown postgres:postgres "$PG_DIR" "$PG_SOCK"
fi
chmod 700 "$PG_DIR" "$PG_SOCK"

# --- 1. cluster ---------------------------------------------------------------------------
if [[ ! -f "$PG_DATA/PG_VERSION" ]]; then
  log "initializing PostgreSQL cluster in $PG_DATA"
  as_pg "$PG_BIN/initdb" -D "$PG_DATA" -U "$PG_OS_USER" -E UTF8 --locale=C \
    --auth-local=peer --auth-host=scram-sha-256 >/dev/null || die "initdb failed"
fi
# Connection settings live in an include file (no shell quoting of paths on the command line).
DEV_CONF="$PG_DATA/wildrush_dev.conf"
as_pg tee "$DEV_CONF" >/dev/null <<EOF
# written by services/scripts/dev_up.sh
listen_addresses = '127.0.0.1'
port = $PG_PORT
unix_socket_directories = '${PG_SOCK//\'/\'\'}'
EOF
if ! as_pg grep -q "^include_if_exists 'wildrush_dev.conf'" "$PG_DATA/postgresql.conf"; then
  printf "\ninclude_if_exists 'wildrush_dev.conf'\n" | as_pg tee -a "$PG_DATA/postgresql.conf" >/dev/null
fi

if pg_running; then
  log "PostgreSQL already running"
else
  log "starting PostgreSQL on 127.0.0.1:$PG_PORT"
  as_pg "$PG_BIN/pg_ctl" -D "$PG_DATA" -l "$PG_LOG" -w -t 60 start >/dev/null \
    || { tail -n 20 "$PG_LOG" >&2 || true; die "pg_ctl start failed"; }
fi
wait_until 30 as_pg "$PG_BIN/pg_isready" -q -h "$PG_SOCK" -p "$PG_PORT" || die "PostgreSQL not ready after 30 s"

# --- 2. role / database / dev env ---------------------------------------------------------
if [[ ! -f "$DEV_ENV" ]]; then
  DB_PASS="$("$PY" -c 'import secrets; print(secrets.token_hex(24))')"
  umask 077
  cat > "$DEV_ENV" <<EOF
# generated by services/scripts/dev_up.sh — local development only (git-ignored .run/)
WR_DATABASE_URL=postgresql+psycopg://$DB_USER:$DB_PASS@127.0.0.1:$PG_PORT/$DB_NAME
WR_BIND=$SVC_HOST:$SVC_PORT
WR_PUBLIC_BASE_URL=$SVC_URL
WR_SERVICE_BUILD=dev
EOF
  umask 022
  log "wrote $DEV_ENV"
fi
chmod 600 "$DEV_ENV"
DB_PASS="$(sed -n 's|^WR_DATABASE_URL=postgresql+psycopg://[^:]*:\([^@]*\)@.*$|\1|p' "$DEV_ENV")"
[[ -n "$DB_PASS" ]] || die "could not read the database password from $DEV_ENV"
psql_admin -v "pw=$DB_PASS" >/dev/null <<SQL || die "role/database setup failed"
SELECT format('CREATE ROLE $DB_USER LOGIN PASSWORD %L', :'pw')
 WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '$DB_USER') \gexec
SELECT format('ALTER ROLE $DB_USER WITH LOGIN PASSWORD %L', :'pw') \gexec
SELECT 'CREATE DATABASE $DB_NAME OWNER $DB_USER'
 WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = '$DB_NAME') \gexec
SQL

# --- 3. migrations -----------------------------------------------------------------------------
load_dev_env
log "applying migrations (alembic upgrade head)"
( cd "$SERVICES_DIR" && timeout 120 "$PY" -m alembic -c "$SERVICES_DIR/alembic.ini" upgrade head ) \
  || die "alembic upgrade failed"

# --- 4. service ----------------------------------------------------------------------------------
if pid_alive "$SVC_PID"; then
  log "service already running (pid $(cat "$SVC_PID"))"
else
  log "starting control service on $SVC_URL"
  (
    cd "$SERVICES_DIR"
    PYTHONPATH="$SERVICES_DIR" nohup setsid "$PY" -m wildrush_svc serve >>"$SVC_LOG" 2>&1 </dev/null &
    echo $! > "$SVC_PID"
  )
fi
if ! wait_until 30 http_get "$SVC_URL/healthz" 3; then
  tail -n 30 "$SVC_LOG" >&2 || true
  die "service did not become healthy within 30 s (log: $SVC_LOG)"
fi
log "healthy: $(http_get "$SVC_URL/healthz" 3)"
log "service  : $SVC_URL   (log $SVC_LOG)"
log "database : 127.0.0.1:$PG_PORT/$DB_NAME   (credentials in $DEV_ENV)"
log "admin CLI: set -a; source $DEV_ENV; set +a; cd services && $PY -m wildrush_svc.admin list-servers"
