"""Alembic owns the schema: models == migrations, round trip works, the app never creates tables."""

from __future__ import annotations

import secrets
from collections.abc import Iterator
from contextlib import contextmanager
from pathlib import Path

import pytest
from alembic import command
from alembic.script import ScriptDirectory
from fastapi.testclient import TestClient
from sqlalchemy import create_engine, text
from sqlalchemy.engine import make_url

from conftest import SERVICES_DIR, alembic_config, make_settings
from wildrush_svc.app import create_app


@contextmanager
def scratch_database(url: str) -> Iterator[str]:
    name = "wr_scratch_" + secrets.token_hex(4)
    admin = create_engine(url, isolation_level="AUTOCOMMIT")
    try:
        with admin.connect() as conn:
            conn.execute(text(f'CREATE DATABASE "{name}"'))
    except Exception as exc:  # external DB without CREATEDB
        admin.dispose()
        pytest.skip(f"cannot create scratch database: {type(exc).__name__}")
    try:
        yield make_url(url).set(database=name).render_as_string(hide_password=False)
    finally:
        with admin.connect() as conn:
            conn.execute(text(f'DROP DATABASE IF EXISTS "{name}" WITH (FORCE)'))
        admin.dispose()


def test_models_match_migrations(migrated_url):
    command.check(alembic_config(migrated_url))  # raises AutogenerateDiffsDetected on drift


def test_single_head_and_round_trip(migrated_url):
    cfg = alembic_config(migrated_url)
    assert len(ScriptDirectory.from_config(cfg).get_heads()) == 1
    with scratch_database(migrated_url) as url:
        scratch = alembic_config(url)
        command.upgrade(scratch, "head")
        command.downgrade(scratch, "base")
        command.upgrade(scratch, "head")
        command.check(scratch)
        eng = create_engine(url)
        with eng.connect() as conn:
            tables = set(conn.execute(text("SELECT tablename FROM pg_tables WHERE schemaname = 'public'")).scalars())
        eng.dispose()
        assert {"accounts", "matches", "match_results", "join_tickets", "alembic_version"} <= tables


def test_app_never_creates_tables(migrated_url):
    source = "\n".join(p.read_text() for p in (SERVICES_DIR / "wildrush_svc").rglob("*.py"))
    assert ".create_all(" not in source and "metadata.create(" not in source
    with scratch_database(migrated_url) as url:
        app = create_app(make_settings(url))
        with TestClient(app, raise_server_exceptions=False) as client:
            assert client.get("/healthz").status_code == 200
            r = client.post("/v1/auth/register", json={"username": "nobody", "password": "password123"})
            assert r.status_code >= 500
        app.state.ctx.engine.dispose()
        eng = create_engine(url)
        with eng.connect() as conn:
            assert conn.execute(text("SELECT to_regclass('public.accounts')")).scalar() is None
        eng.dispose()


def test_migration_files_are_plain_python():
    versions = sorted((SERVICES_DIR / "alembic" / "versions").glob("*.py"))
    assert [p.name for p in versions] == ["0001_initial_schema.py", "0002_nullable_history_fighter.py"]
    # no credentials in alembic.ini: the URL comes from WR_DATABASE_URL at runtime
    ini_lines = Path(SERVICES_DIR / "alembic.ini").read_text().splitlines()
    assert not any(line.strip().startswith("sqlalchemy.url") for line in ini_lines)
