class_name ArenaLayout
extends RefCounted
## Parsed arena layout (game/data/arena/*.json, generated by tools/arena/gen_layout.py).

const BRIARPORT_PATH: String = "res://data/arena/briarport_layout.json"

var data: Dictionary = {}
var zones: Array = []
var spawns: Array = []
var perch_ledges: Array = []      # [{a, b, normal}] Vector3s


static func load_file(path: String = BRIARPORT_PATH) -> ArenaLayout:
	var l := ArenaLayout.new()
	var txt: String = FileAccess.get_file_as_string(path)
	var parsed: Variant = JSON.parse_string(txt)
	if typeof(parsed) != TYPE_DICTIONARY:
		push_error("ArenaLayout: cannot parse " + path)
		return l
	l.set_data(parsed)
	return l


static func from_dict(d: Dictionary) -> ArenaLayout:
	var l := ArenaLayout.new()
	l.set_data(d)
	return l


func set_data(d: Dictionary) -> void:
	data = d
	zones = d.get("zones", [])
	spawns = d.get("spawns", [])
	perch_ledges.clear()
	for p in d.get("perch_ledges", []):
		perch_ledges.append({"a": v3(p["a"]), "b": v3(p["b"]), "normal": v3(p["normal"]), "id": p.get("id", "")})


static func v3(a: Array) -> Vector3:
	return Vector3(float(a[0]), float(a[1]), float(a[2]))


func zone(id: String) -> Dictionary:
	for z in zones:
		if String(z["id"]) == id:
			return z
	return {}


func zone_center(id: String) -> Vector3:
	var z: Dictionary = zone(id)
	return v3(z["center"]) if not z.is_empty() else Vector3.ZERO


func spawn_for(team: int) -> Dictionary:
	for s in spawns:
		if int(s["team"]) == team:
			return s
	return {}


func spawn_points(team: int) -> Array:
	var out: Array = []
	for p in spawn_for(team).get("points", []):
		out.append({"pos": Vector3(float(p[0]), float(p[1]), float(p[2])), "yaw": float(p[3])})
	return out


func spawn_volume(team: int) -> AABB:
	var s: Dictionary = spawn_for(team)
	if s.is_empty():
		return AABB()
	var mn: Vector3 = v3(s["protect"]["min"])
	var mx: Vector3 = v3(s["protect"]["max"])
	return AABB(mn, mx - mn)


func spawn_exits(team: int) -> Array:
	var out: Array = []
	for e in spawn_for(team).get("exits", []):
		out.append(v3(e))
	return out


func surface_at(p: Vector3) -> String:
	## Floor surface under a point (for footstep audio). Puddles override to "wet".
	for d in data.get("decor", []):
		if String(d["kind"]) == "puddle":
			var c: Vector3 = v3(d["pos"])
			if Vector2(p.x - c.x, p.z - c.z).length() < float(d.get("scale", 1.0)):
				return "wet"
	var best: String = "stone"
	var best_top: float = -INF
	for f in data.get("floors", []):
		var mn: Array = f["min"]
		var mx: Array = f["max"]
		if p.x >= float(mn[0]) and p.x <= float(mx[0]) and p.z >= float(mn[2]) and p.z <= float(mx[2]):
			var top: float = float(mx[1])
			if top <= p.y + 0.3 and top > best_top:
				best_top = top
				best = String(f.get("surface", "stone"))
	return best
